ARG IMAGE_TAG=latest
FROM envoyproxy/envoy:${IMAGE_TAG}
RUN apt-get update && apt-get -y install tcpdump
RUN mkdir -p /var/log/envoy
EXPOSE 80 443 8080 9901
CMD envoy \
    -c ${ENVOY_CONFIG} \
    --service-zone ${ENVOY_ZONE} \
    --log-level ${ENVOY_LOGLEVEL} \
    --log-path /var/log/envoy/application.log \
    --log-format '{"time": "%Y-%m-%d %T.%e", "level": "%l", "type": "%n", "message": "%v"}'
