FROM python:3.7

MAINTAINER Vasilios Syrakis <vsyrakis@atlassian.com>

ADD requirements-dev.txt /requirements-dev.txt
RUN pip install --upgrade pip
RUN pip install --upgrade -r /requirements-dev.txt

ADD . /proj
WORKDIR /proj
RUN python setup.py build_sphinx
