FROM python:3.8

MAINTAINER Vasilios Syrakis <vsyrakis@atlassian.com>

RUN pip install --upgrade pip
ADD requirements.txt /requirements.txt
ADD requirements-dev.txt /requirements-dev.txt
RUN pip install -r /requirements-dev.txt

ADD . /proj
WORKDIR /proj
RUN python setup.py sdist
RUN pip install dist/sovereign-*.tar.gz
