FROM python:3.7

MAINTAINER Vasilios Syrakis <vsyrakis@atlassian.com>

ADD requirements-dev.txt /requirements-dev.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements-dev.txt

ADD . /proj
WORKDIR /proj
RUN python setup.py sdist
RUN pip install dist/sovereign-*.tar.gz
RUN sphinx-apidoc -o /proj/docs src/sovereign
CMD sphinx-build -b html "/proj/docs" "/proj/src/sovereign/docs"
