site_name: Sovereign
site_description: Extensible JSON control-plane for Lyft's Envoy proxy, written in Python
site_url: https://vsyrakis.bitbucket.io/sovereign/docs/
theme:
  name: material
  palette:
    primary: CCCCCC
    accent: blue
  #logo: img/icon-white.svg
  #favicon: img/favicon.png
  language: en
repo_name: cetanu/sovereign
repo_url: https://github.com/cetanu/sovereign

nav:
  - Sovereign: index.md
  - Terminology: terminology.md
  - Tutorial:
      - tutorial/first-steps.md
      - tutorial/sources.md
      - tutorial/templates.md
      - tutorial/running-sovereign.md
  - Advanced:
      - advanced/modifiers.md
      - advanced/custom-sources.md
  - Settings and Environment Variables: settings.md


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format ''

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cetanu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/atl_vsyrakis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/svasilios/

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
