resources:
  {% for instance in instances %}
    {% for domain in instance.domains %}
  - name: {{ instance.name }}_scoped_route
    route_configuration_name: {{ instance.name }}_routes
    key:
      fragments:
        - string_key: {{ domain }}
    {% endfor %}
  {% endfor %}
