version_info: '{{ version|default(0) }}'
resources:
  - '@type': type.googleapis.com/envoy.api.v2.RouteConfiguration
    name: service_instances_rds # This has to match the route_configuration_name specified in the Listener configuration
    virtual_hosts:
    {% for instance in instances %}
      {% set service_name = instance.get('alt_service_name', instance.instance_id) %}
    {% for vhost in instance.parameters.vhosts %}
      {% if vhost.domains != [] %}
      - name: {{ service_name }}-{{ vhost.name }}
        domains:
        {% for domain in vhost.domains %}
          - '{{ domain }}'
          - '{{ domain }}.'
        {% endfor %}
        routes:
        {% for route in vhost.routes %}
        - {{ route|tojson }}
        {% endfor %}
        - match:
            prefix: /
          route:
            cluster: {{ service_name }}-{{ vhost.clusters.0.name }}
            {% if vhost.rewrite == 'no' %}
            {% elif vhost.rewrite == 'yes' %}
            auto_host_rewrite: true
            {% elif vhost.rewrite|length %}
            host_rewrite: {{ vhost.rewrite }}
            {% endif %}
      {% endif %}
    {% endfor %}
    {% endfor %}
